package mtnm.huawei.com.HW_mstpInventoryMgr;


/**
 * Generated from IDL interface "HW_MSTPInventoryMgr_I".
 *
 * @author JacORB IDL compiler V 3.9
 * @version generated at 13/07/2021 04:51:40 PM
 */

public interface HW_MSTPInventoryMgr_IOperations
	extends mtnm.tmforum.org.common.Common_IOperations
{
	/* constants */
	/* operations  */
	void getAllMstpEndPoints(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] meName, mtnm.huawei.com.HW_mstpInventoryMgr.HW_MSTPEndPointType_T[] typeList, int how_many, mtnm.huawei.com.HW_mstpInventoryMgr.HW_MSTPEndPointList_THolder endPointList, mtnm.huawei.com.HW_mstpInventoryMgr.HW_MSTPEndPointIterator_IHolder endPointIt) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getAllMstpEndPointNames(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] meName, mtnm.huawei.com.HW_mstpInventoryMgr.HW_MSTPEndPointType_T[] typeList, int how_many, mtnm.tmforum.org.globaldefs.NamingAttributesList_THolder nameList, mtnm.tmforum.org.globaldefs.NamingAttributesIterator_IHolder nameIt) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getMstpEndPoint(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] endPointName, mtnm.huawei.com.HW_mstpInventoryMgr.HW_MSTPEndPoint_THolder endPoint) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void setMstpEndPoint(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] endPointName, mtnm.tmforum.org.transmissionParameters.LayeredParameters_T[] paraList, mtnm.huawei.com.HW_mstpInventoryMgr.HW_MSTPEndPoint_THolder endPoint) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getAllVBs(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] meName, int how_many, mtnm.huawei.com.HW_mstpInventoryMgr.HW_VirtualBridgeList_THolder vbList, mtnm.huawei.com.HW_mstpInventoryMgr.HW_VirtualBridgeIterator_IHolder vbIt) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getAllVBNames(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] meName, int how_many, mtnm.tmforum.org.globaldefs.NamingAttributesList_THolder nameList, mtnm.tmforum.org.globaldefs.NamingAttributesIterator_IHolder nameIt) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getVirtualBridge(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] vbName, mtnm.huawei.com.HW_mstpInventoryMgr.HW_VirtualBridge_THolder vb) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void createVirtualBridge(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] equipmentName, short vbId, java.lang.String vbName, mtnm.huawei.com.HW_mstpInventoryMgr.HW_VirtualBridge_THolder vb) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void deleteVirtualBridge(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] vbName) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void createVLAN(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] vbName, short vlanId, mtnm.tmforum.org.globaldefs.NameAndStringValue_T[][] forwardTPList, mtnm.huawei.com.HW_mstpInventoryMgr.HW_VirtualLAN_THolder vlan) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void deleteVLAN(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] vlanName) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getAllVLANs(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] vbName, int how_many, mtnm.huawei.com.HW_mstpInventoryMgr.HW_VirtualLANList_THolder vlanList, mtnm.huawei.com.HW_mstpInventoryMgr.HW_VirtualLANIterator_IHolder vlanIt) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getAllVLANNames(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] vbName, int how_many, mtnm.tmforum.org.globaldefs.NamingAttributesList_THolder nameList, mtnm.tmforum.org.globaldefs.NamingAttributesIterator_IHolder nameIt) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getVLAN(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] vlanName, mtnm.huawei.com.HW_mstpInventoryMgr.HW_VirtualLAN_THolder vlan) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void addVLANForwardPort(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] vlanName, mtnm.tmforum.org.globaldefs.NameAndStringValue_T[][] forwardTPList, mtnm.huawei.com.HW_mstpInventoryMgr.HW_VirtualLAN_THolder vlan) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void delVLANForwardPort(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] vlanName, mtnm.tmforum.org.globaldefs.NameAndStringValue_T[][] forwardTPList, mtnm.huawei.com.HW_mstpInventoryMgr.HW_VirtualLAN_THolder vlan) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void setVLANData(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] vlanName, mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] paraList, mtnm.huawei.com.HW_mstpInventoryMgr.HW_VirtualLAN_THolder vlan) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getBindingPath(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] endPointName, mtnm.huawei.com.HW_mstpInventoryMgr.HW_MSTPBindingPathList_THolder bindingPathList) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void addBindingPath(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] endPointName, mtnm.tmforum.org.terminationPoint.Directionality_T bindingDirect, mtnm.tmforum.org.globaldefs.NameAndStringValue_T[][] pathList, mtnm.huawei.com.HW_mstpInventoryMgr.HW_MSTPBindingPathList_THolder bindingPathList) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void delBindingPath(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] endPointName, mtnm.tmforum.org.terminationPoint.Directionality_T bindingDirect, mtnm.tmforum.org.globaldefs.NameAndStringValue_T[][] pathList, mtnm.huawei.com.HW_mstpInventoryMgr.HW_MSTPBindingPathList_THolder bindingPathList) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getLCASState(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] endPointName, org.omg.CORBA.BooleanHolder enableState) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void setLCASState(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] endPointName, boolean enableState) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getAllContainedCurrentTPNames(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] endPointName, short[] layerRateList, int how_many, mtnm.tmforum.org.globaldefs.NamingAttributesList_THolder nameList, mtnm.tmforum.org.globaldefs.NamingAttributesIterator_IHolder nameIt) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getAllContainedInUseTPNames(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] endPointName, short[] layerRateList, int how_many, mtnm.tmforum.org.globaldefs.NamingAttributesList_THolder nameList, mtnm.tmforum.org.globaldefs.NamingAttributesIterator_IHolder nameIt) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void createQosRule(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] equipmentName, mtnm.huawei.com.HW_mstpInventoryMgr.HW_QosType_T qosType, mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] paraList, mtnm.huawei.com.HW_mstpInventoryMgr.HW_QosRule_THolder qosRule) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void setQosRule(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] qosRuleName, mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] paraList, mtnm.huawei.com.HW_mstpInventoryMgr.HW_QosRule_THolder qosRule) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void createFlow(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] equipmentName, mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] paraList, mtnm.huawei.com.HW_mstpInventoryMgr.HW_Flow_THolder flow) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getAllQosRules(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] meName, int how_many, mtnm.huawei.com.HW_mstpInventoryMgr.HW_QosRuleList_THolder qosRuleList, mtnm.huawei.com.HW_mstpInventoryMgr.HW_QosRuleIterator_IHolder qosRuleIt) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getAllQosRuleNames(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] meName, int how_many, mtnm.tmforum.org.globaldefs.NamingAttributesList_THolder nameList, mtnm.tmforum.org.globaldefs.NamingAttributesIterator_IHolder nameIt) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getQosRule(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] qosRuleName, mtnm.huawei.com.HW_mstpInventoryMgr.HW_QosRule_THolder qosRule) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void deleteQosRule(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] qosRuleName) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getAllFlows(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] meName, int how_many, mtnm.huawei.com.HW_mstpInventoryMgr.HW_FlowList_THolder flowList, mtnm.huawei.com.HW_mstpInventoryMgr.HW_FlowIterator_IHolder flowIt) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getAllFlowNames(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] meName, int how_many, mtnm.tmforum.org.globaldefs.NamingAttributesList_THolder nameList, mtnm.tmforum.org.globaldefs.NamingAttributesIterator_IHolder nameIt) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getFlow(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] flowName, mtnm.huawei.com.HW_mstpInventoryMgr.HW_Flow_THolder flow) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void setFlow(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] flowName, mtnm.tmforum.org.globaldefs.NameAndStringValue_T[][] qosRuleNames, mtnm.huawei.com.HW_mstpInventoryMgr.HW_Flow_THolder flow) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void deleteFlow(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] flowName) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void createLinkAggregationGroup(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] meName, mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] paraList, mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] mainPortName, mtnm.tmforum.org.globaldefs.NameAndStringValue_T[][] branchPortNameList, mtnm.huawei.com.HW_mstpInventoryMgr.HW_LinkAggregationGroup_THolder lag) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getAllLinkAggregationGroups(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] meName, int how_many, mtnm.huawei.com.HW_mstpInventoryMgr.HW_LinkAggregationGroupList_THolder lagList, mtnm.huawei.com.HW_mstpInventoryMgr.HW_LinkAggregationGroupIterator_IHolder lagIt) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getAllLinkAggregationGroupNames(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] meName, int how_many, mtnm.tmforum.org.globaldefs.NamingAttributesList_THolder nameList, mtnm.tmforum.org.globaldefs.NamingAttributesIterator_IHolder nameIt) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getLinkAggregationGroup(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] lagName, mtnm.huawei.com.HW_mstpInventoryMgr.HW_LinkAggregationGroup_THolder lag) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getAvailablePortNames(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] equipmentName, int how_many, mtnm.tmforum.org.globaldefs.NamingAttributesList_THolder nameList, mtnm.tmforum.org.globaldefs.NamingAttributesIterator_IHolder nameIt) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void modifyLinkAggregationGroup(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] lagName, mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] paraList, mtnm.tmforum.org.globaldefs.NameAndStringValue_T[][] addedBranchPortNameList, mtnm.tmforum.org.globaldefs.NameAndStringValue_T[][] deletedBranchPortNameList, mtnm.huawei.com.HW_mstpInventoryMgr.HW_LinkAggregationGroup_THolder lag) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void deleteLinkAggregationGroup(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] lagName) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void setMstpEndPointShapingQueue(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] endPointName, mtnm.huawei.com.HW_mstpInventoryMgr.ShapingQueueList_THolder shapingQueueList) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getMstpEndPointShapingQueue(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] endPointName, mtnm.huawei.com.HW_mstpInventoryMgr.ShapingQueueList_THolder shapingQueueList) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getAllSpanningTrees(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] equipmentName, int how_many, mtnm.huawei.com.HW_mstpInventoryMgr.HW_SpanningTreeList_THolder spanningTreeList, mtnm.huawei.com.HW_mstpInventoryMgr.HW_SpanningTreeIterator_IHolder spanningTreeIt) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getAllSpanningTreeNames(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] equipmentName, int how_many, mtnm.tmforum.org.globaldefs.NamingAttributesList_THolder nameList, mtnm.tmforum.org.globaldefs.NamingAttributesIterator_IHolder nameIt) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getSpanningTree(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] spanningTreeName, mtnm.huawei.com.HW_mstpInventoryMgr.HW_SpanningTree_THolder spanningTree) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void setSTProtocolParam(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] spanningTreeName, mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] paraList) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void setSTBridgeParam(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] spanningTreeName, mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] paraList) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void setSTPortParam(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] spanningTreeName, mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] portName, mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] paraList) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
}
