package mtnm.huawei.com.HW_vpnManager;


/**
 * Generated from IDL interface "HW_VPNMgr_I".
 *
 * @author JacORB IDL compiler V 3.9
 * @version generated at 13/07/2021 04:51:40 PM
 */

public interface HW_VPNMgr_IOperations
	extends mtnm.tmforum.org.common.Common_IOperations
{
	/* constants */
	/* operations  */
	void createMFDFr(mtnm.huawei.com.HW_vpnManager.MatrixFlowDomainFragment_T createData, mtnm.tmforum.org.subnetworkConnection.TPDataList_THolder tpsToModify, mtnm.huawei.com.HW_vpnManager.MatrixFlowDomainFragment_THolder theMFDFr, mtnm.tmforum.org.globaldefs.NamingAttributesList_THolder notConnectableCPTPList, mtnm.tmforum.org.globaldefs.NamingAttributesList_THolder parameterProblemsTPList, org.omg.CORBA.StringHolder errorReason) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void modifyMFDFr(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] mfdfrName, mtnm.huawei.com.HW_vpnManager.MFDFrModifyData_T modifyData, mtnm.huawei.com.HW_vpnManager.MatrixFlowDomainFragment_THolder theMFDFr, mtnm.tmforum.org.globaldefs.NamingAttributesList_THolder notConnectableCPTPList, mtnm.tmforum.org.globaldefs.NamingAttributesList_THolder parameterProblemsTPList, org.omg.CORBA.StringHolder errorReason) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void deleteMFDFr(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] mfdfrName) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void activateMFDFr(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] mfdfrName, mtnm.tmforum.org.subnetworkConnection.TPDataList_THolder tpsToModify, mtnm.huawei.com.HW_vpnManager.MatrixFlowDomainFragment_THolder theMFDFr, org.omg.CORBA.StringHolder errorReason) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void deactivateMFDFr(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] mfdfrName, mtnm.tmforum.org.subnetworkConnection.TPDataList_THolder tpsToModify, mtnm.huawei.com.HW_vpnManager.MatrixFlowDomainFragment_THolder theMFDFr, org.omg.CORBA.StringHolder errorReason) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getAllMFDFrs(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] meName, short[] connectionRateList, int how_many, mtnm.huawei.com.HW_vpnManager.MatrixFlowDomainFragmentList_THolder mfdfrList, mtnm.huawei.com.HW_vpnManager.MFDFrIterator_IHolder mfdfrIt) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getAllMFDFrNames(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] meName, short[] connectionRateList, int how_many, mtnm.tmforum.org.globaldefs.NamingAttributesList_THolder nameList, mtnm.tmforum.org.globaldefs.NamingAttributesIterator_IHolder nameIt) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getMFDFr(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] mfdfrName, mtnm.huawei.com.HW_vpnManager.MatrixFlowDomainFragment_THolder theMFDFr) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getAllTrafficTrunksWithME(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] managedElementName, short[] connectionRateList, int how_many, mtnm.huawei.com.HW_vpnManager.TrafficTrunkList_THolder trafficTrunkList, mtnm.huawei.com.HW_vpnManager.TrafficTrunkIterator_IHolder trafficTrunkIt) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getAllTrafficTrunkNamesWithME(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] managedElementName, short[] connectionRateList, int how_many, mtnm.tmforum.org.globaldefs.NamingAttributesList_THolder nameList, mtnm.tmforum.org.globaldefs.NamingAttributesIterator_IHolder nameIt) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void createTrafficTrunk(mtnm.huawei.com.HW_vpnManager.TrafficTrunkCreateData_T createData, mtnm.huawei.com.HW_vpnManager.TrafficTrunk_THolder theTrafficTrunk, org.omg.CORBA.StringHolder errorReason) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void deleteTrafficTrunk(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] trafficTrunkName) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void activateTrafficTrunk(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] trafficTrunkName, mtnm.huawei.com.HW_vpnManager.TrafficTrunk_THolder theTrafficTrunk, org.omg.CORBA.StringHolder errorReason) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void activateAllTrafficTrunks(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[][] trafficTrunkNameList, mtnm.huawei.com.HW_vpnManager.TrafficTrunkList_THolder trafficTrunkList, org.omg.CORBA.StringHolder errorReason) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void deactivateTrafficTrunk(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] trafficTrunkName, mtnm.huawei.com.HW_vpnManager.TrafficTrunk_THolder theTrafficTrunk, org.omg.CORBA.StringHolder errorReason) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getTrafficTrunk(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] trafficTrunkName, mtnm.huawei.com.HW_vpnManager.TrafficTrunk_THolder trafficTrunk) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void modifyTrafficTrunk(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] trafficTrunkName, mtnm.huawei.com.HW_vpnManager.TrafficTrunkModifyData_T modifyData, mtnm.huawei.com.HW_vpnManager.TrafficTrunk_THolder newTrafficTrunk, org.omg.CORBA.StringHolder errorReason) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getAllIPCrossConnections(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] managedElementName, short[] connectionRateList, int how_many, mtnm.huawei.com.HW_vpnManager.IPCrossConnectionList_THolder ipCCList, mtnm.huawei.com.HW_vpnManager.IPCrossConnectionIterator_IHolder ipCCIt) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getAllIPCrossConnectionNames(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] managedElementName, short[] connectionRateList, int how_many, mtnm.tmforum.org.globaldefs.NamingAttributesList_THolder nameList, mtnm.tmforum.org.globaldefs.NamingAttributesIterator_IHolder nameIt) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void createIPCrossConnections(mtnm.huawei.com.HW_vpnManager.IPCrossConnection_T[] ipCCList, mtnm.huawei.com.HW_vpnManager.IPCrossConnectionList_THolder successedIPCCList, mtnm.huawei.com.HW_vpnManager.IPCrossConnectionList_THolder failedIPCCList) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void deleteIPCrossConnections(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[][] ipCCNameList, mtnm.tmforum.org.globaldefs.NamingAttributesList_THolder successedIPCCNameList, mtnm.tmforum.org.globaldefs.NamingAttributesList_THolder failedIPCCNameList) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getIPCrossConnection(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] ipCCName, mtnm.huawei.com.HW_vpnManager.IPCrossConnection_THolder ipCC) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void modifyIPCrossConnection(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] ipCCName, mtnm.tmforum.org.transmissionParameters.LayeredParameters_T transmissionParams, mtnm.huawei.com.HW_vpnManager.IPCrossConnection_THolder newIPCC, org.omg.CORBA.StringHolder errorReason) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void activateIPCrossConnections(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[][] ipCCNameList, mtnm.tmforum.org.globaldefs.NamingAttributesList_THolder successedIPCCNameList, mtnm.tmforum.org.globaldefs.NamingAttributesList_THolder failedIPCCNameList, org.omg.CORBA.StringHolder errorReason) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void deactivateIPCrossConnections(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[][] ipCCNameList, mtnm.tmforum.org.globaldefs.NamingAttributesList_THolder successedIPCCNameList, mtnm.tmforum.org.globaldefs.NamingAttributesList_THolder failedIPCCNameList, org.omg.CORBA.StringHolder errorReason) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void createFDFr(mtnm.huawei.com.HW_vpnManager.FDFrCreateData_T createData, mtnm.tmforum.org.flowDomain.ConnectivityRequirement_T connectivityRequirement, mtnm.tmforum.org.subnetworkConnection.TPDataList_THolder endTPs, mtnm.tmforum.org.subnetworkConnection.TPDataList_THolder internalTPs, mtnm.huawei.com.HW_vpnManager.MatrixFlowDomainFragmentList_THolder mfdfrs, mtnm.tmforum.org.subnetworkConnection.TPDataList_THolder tpsToModify, mtnm.huawei.com.HW_vpnManager.FlowDomainFragment_THolder theFDFr, org.omg.CORBA.StringHolder errorReason) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void modifyFDFr(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] fdfrName, mtnm.huawei.com.HW_vpnManager.FDFrModifyData_T fdfrModifyData, mtnm.tmforum.org.subnetworkConnection.TPDataList_THolder tpsToModify, mtnm.tmforum.org.subnetworkConnection.GradesOfImpact_T tolerableImpact, mtnm.huawei.com.HW_vpnManager.FlowDomainFragment_THolder newFDFr, org.omg.CORBA.StringHolder errorReason) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void deleteFDFr(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] fdfrName, mtnm.tmforum.org.subnetworkConnection.TPDataList_THolder tpsToModify) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void activateFDFr(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] fdfrName, mtnm.huawei.com.HW_vpnManager.FlowDomainFragment_THolder fdfr) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void deactivateFDFr(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] fdfrName, mtnm.huawei.com.HW_vpnManager.FlowDomainFragment_THolder fdfr) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getTrafficTrunkRoute(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] trafficTrunkName, mtnm.huawei.com.HW_vpnManager.IPCrossConnectionList_THolder route) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getAllFDFrs(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] fdName, int how_many, short[] connectionRateList, mtnm.huawei.com.HW_vpnManager.FlowDomainFragmentList_THolder fdfrList, mtnm.huawei.com.HW_vpnManager.FDFrIterator_IHolder fdfrIt) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getAllFDFrNames(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] fdName, int how_many, short[] connectionRateList, mtnm.tmforum.org.globaldefs.NamingAttributesList_THolder nameList, mtnm.tmforum.org.globaldefs.NamingAttributesIterator_IHolder nameIt) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getFDFr(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] fdfrName, mtnm.huawei.com.HW_vpnManager.FlowDomainFragment_THolder theFDFr) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getFDFrRoute(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] fdfrName, boolean includeHigherOrderCCs, mtnm.huawei.com.HW_vpnManager.FDFrRoute_THolder route) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getFDFrServerTrail(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] fdfrName, mtnm.tmforum.org.globaldefs.NamingAttributesList_THolder serverNameList) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getAllTrafficTrunks(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] fdName, short[] connectionRateList, int how_many, mtnm.huawei.com.HW_vpnManager.TrafficTrunkList_THolder trafficTrunkList, mtnm.huawei.com.HW_vpnManager.TrafficTrunkIterator_IHolder trafficTrunkIt) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getAllTrafficTrunkNames(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] fdName, short[] connectionRateList, int how_many, mtnm.tmforum.org.globaldefs.NamingAttributesList_THolder nameList, mtnm.tmforum.org.globaldefs.NamingAttributesIterator_IHolder nameIt) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getIPRoutes(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] trafficTrunkName, mtnm.huawei.com.HW_vpnManager.IPCrossConnectionList_THolder routes) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getTrafficTrunksByNativeEmsName(java.lang.String nativeEmsName, mtnm.huawei.com.HW_vpnManager.TrafficTrunkList_THolder trafficTrunkList) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getTrafficTrunksByUserLabel(java.lang.String userLabel, mtnm.huawei.com.HW_vpnManager.TrafficTrunkList_THolder trafficTrunkList) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getTrafficTrunksWithTP(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] tpName, int how_many, mtnm.huawei.com.HW_vpnManager.TrafficTrunkList_THolder trafficTrunkList, mtnm.huawei.com.HW_vpnManager.TrafficTrunkIterator_IHolder trafficTrunkIt) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getFDFrsByUserLabel(java.lang.String userLabel, mtnm.huawei.com.HW_vpnManager.FlowDomainFragmentList_THolder fdfrList) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getFDFrsWithME(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] managedElementName, short[] connectionRateList, int how_many, mtnm.huawei.com.HW_vpnManager.FlowDomainFragmentList_THolder fdfrList, mtnm.huawei.com.HW_vpnManager.FDFrIterator_IHolder fdfrIt) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getFDFrsWithTP(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] cptpName, int how_many, mtnm.huawei.com.HW_vpnManager.FlowDomainFragmentList_THolder fdfrList, mtnm.huawei.com.HW_vpnManager.FDFrIterator_IHolder fdfrIt) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getSelfLearningMACAddressTable(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[][] nameList, int how_many, mtnm.huawei.com.HW_vpnManager.SelfLearningMACAddressTableList_THolder tableList, mtnm.huawei.com.HW_vpnManager.SelfLearningMACAddressTableIterator_IHolder tableIt) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getIPRoutesByTrafficTrunks(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[][] trafficTrunkNameList, mtnm.huawei.com.HW_vpnManager.IPRouteInfoList_THolder routeInfoList) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getFDFrRoutes(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[][] fdfrNameList, mtnm.huawei.com.HW_vpnManager.FDFrRouteInfoList_THolder routeInfoList) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
}
