package mtnm.tmforum.org.multiLayerSubnetwork;


/**
 * Generated from IDL interface "MultiLayerSubnetworkMgr_I".
 *
 * @author JacORB IDL compiler V 3.9
 * @version generated at 13/07/2021 04:51:40 PM
 */

public interface MultiLayerSubnetworkMgr_IOperations
	extends mtnm.tmforum.org.common.Common_IOperations
{
	/* constants */
	/* operations  */
	void getAllManagedElements(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] subnetName, int how_many, mtnm.tmforum.org.managedElement.ManagedElementList_THolder meList, mtnm.tmforum.org.managedElement.ManagedElementIterator_IHolder meIt) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getAllManagedElementNames(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] subnetName, int how_many, mtnm.tmforum.org.globaldefs.NamingAttributesList_THolder nameList, mtnm.tmforum.org.globaldefs.NamingAttributesIterator_IHolder nameIt) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getMultiLayerSubnetwork(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] subnetName, mtnm.tmforum.org.multiLayerSubnetwork.MultiLayerSubnetwork_THolder subnetwork) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getAllTopologicalLinks(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] subnetName, int how_many, mtnm.tmforum.org.topologicalLink.TopologicalLinkList_THolder topoList, mtnm.tmforum.org.topologicalLink.TopologicalLinkIterator_IHolder topoIt) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getAllTopologicalLinkNames(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] subnetName, int how_many, mtnm.tmforum.org.globaldefs.NamingAttributesList_THolder nameList, mtnm.tmforum.org.globaldefs.NamingAttributesIterator_IHolder nameIt) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getAllInternalTopologicalLinks(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] meName, int how_many, mtnm.tmforum.org.topologicalLink.TopologicalLinkList_THolder topoList, mtnm.tmforum.org.topologicalLink.TopologicalLinkIterator_IHolder topoIt) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getAllInternalTopologicalLinkNames(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] meName, int how_many, mtnm.tmforum.org.globaldefs.NamingAttributesList_THolder nameList, mtnm.tmforum.org.globaldefs.NamingAttributesIterator_IHolder nameIt) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getTopologicalLink(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] topoLinkName, mtnm.tmforum.org.topologicalLink.TopologicalLink_THolder topoLink) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getAllEdgePoints(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] subnetName, short[] tpLayerRateList, short[] connectionLayerRateList, int how_many, mtnm.tmforum.org.terminationPoint.TerminationPointList_THolder tpList, mtnm.tmforum.org.terminationPoint.TerminationPointIterator_IHolder tpIt) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getAllEdgePointNames(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] subnetName, short[] layerRateList, short[] connectionLayerRateList, int how_many, mtnm.tmforum.org.globaldefs.NamingAttributesList_THolder nameList, mtnm.tmforum.org.globaldefs.NamingAttributesIterator_IHolder nameIt) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getAssociatedTP(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] tpName, mtnm.tmforum.org.terminationPoint.TerminationPointList_THolder tpList) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getTPGroupingRelationships(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] tpName, int how_many, mtnm.tmforum.org.globaldefs.NamingAttributesList_THolder nameList, mtnm.tmforum.org.globaldefs.NamingAttributesIterator_IHolder nameIt) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getAllSubnetworkConnections(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] subnetName, short[] connectionRateList, int how_many, mtnm.tmforum.org.subnetworkConnection.SubnetworkConnectionList_THolder sncList, mtnm.tmforum.org.subnetworkConnection.SNCIterator_IHolder sncIt) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getAllSubnetworkConnectionNames(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] subnetName, short[] connectionRateList, int how_many, mtnm.tmforum.org.globaldefs.NamingAttributesList_THolder nameList, mtnm.tmforum.org.globaldefs.NamingAttributesIterator_IHolder nameIt) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getAllSubnetworkConnectionsWithTP(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] tpName, short[] connectionRateList, int how_many, mtnm.tmforum.org.subnetworkConnection.SubnetworkConnectionList_THolder sncList, mtnm.tmforum.org.subnetworkConnection.SNCIterator_IHolder sncIt) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getAllSubnetworkConnectionNamesWithTP(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] tpName, short[] connectionRateList, int how_many, mtnm.tmforum.org.globaldefs.NamingAttributesList_THolder nameList, mtnm.tmforum.org.globaldefs.NamingAttributesIterator_IHolder nameIt) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getRoute(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] sncName, boolean includeHigherOrderCCs, mtnm.tmforum.org.subnetworkConnection.Route_THolder route) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getRoutes(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[][] sncNameList, boolean includeHigherOrderCCs, mtnm.tmforum.org.subnetworkConnection.RouteInfoList_THolder routeInfoList) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getRouteAndTopologicalLinksBySNCs(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[][] sncNameList, int how_many, mtnm.tmforum.org.multiLayerSubnetwork.RouteAndTopologicalLinkList_THolder routeAndTlList, mtnm.tmforum.org.multiLayerSubnetwork.RouteAndTopologicalLinkIterator_IHolder routeAndTlIt) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getSNC(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] sncName, mtnm.tmforum.org.subnetworkConnection.SubnetworkConnection_THolder snc) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getSNCs(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[][] sncNameList, mtnm.tmforum.org.subnetworkConnection.SubnetworkConnectionList_THolder sncList) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getSNCsByEndObjectName(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] aEndObjectName, mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] zEndObjectName, short[] connectionRateList, mtnm.tmforum.org.subnetworkConnection.SubnetworkConnectionList_THolder sncList) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getSNCsByNativeEmsName(java.lang.String nativeEmsName, int how_many, mtnm.tmforum.org.subnetworkConnection.SubnetworkConnectionList_THolder sncList, mtnm.tmforum.org.subnetworkConnection.SNCIterator_IHolder sncIt) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getSNCsByUserLabel(java.lang.String userLabel, mtnm.tmforum.org.subnetworkConnection.SubnetworkConnectionList_THolder sncList) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void createSNC(mtnm.tmforum.org.subnetworkConnection.SNCCreateData_T createData, mtnm.tmforum.org.subnetworkConnection.GradesOfImpact_T tolerableImpact, mtnm.tmforum.org.multiLayerSubnetwork.EMSFreedomLevel_T emsFreedomLevel, mtnm.tmforum.org.subnetworkConnection.SubnetworkConnection_THolder theSNC, org.omg.CORBA.StringHolder errorReason) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void modifySNC(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] sncName, java.lang.String routeId, mtnm.tmforum.org.subnetworkConnection.SNCModifyData_T SNCModifyData, mtnm.tmforum.org.subnetworkConnection.GradesOfImpact_T tolerableImpact, mtnm.tmforum.org.subnetworkConnection.ProtectionEffort_T tolerableImpactEffort, mtnm.tmforum.org.multiLayerSubnetwork.EMSFreedomLevel_T emsFreedomLevel, mtnm.tmforum.org.subnetworkConnection.TPDataList_THolder tpsToModify, mtnm.tmforum.org.subnetworkConnection.SubnetworkConnection_THolder newSNC, org.omg.CORBA.StringHolder errorReason) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void activateSNC(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] sncName, mtnm.tmforum.org.subnetworkConnection.GradesOfImpact_T tolerableImpact, mtnm.tmforum.org.multiLayerSubnetwork.EMSFreedomLevel_T emsFreedomLevel, mtnm.tmforum.org.subnetworkConnection.TPDataList_THolder tpsToModify, mtnm.tmforum.org.subnetworkConnection.SubnetworkConnection_THolder theSNC, org.omg.CORBA.StringHolder errorReason) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void createAndActivateSNC(mtnm.tmforum.org.subnetworkConnection.SNCCreateData_T createData, mtnm.tmforum.org.subnetworkConnection.GradesOfImpact_T tolerableImpact, mtnm.tmforum.org.multiLayerSubnetwork.EMSFreedomLevel_T emsFreedomLevel, mtnm.tmforum.org.subnetworkConnection.TPDataList_THolder tpsToModify, mtnm.tmforum.org.subnetworkConnection.SubnetworkConnection_THolder theSNC, org.omg.CORBA.StringHolder errorReason) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void deactivateSNC(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] sncName, mtnm.tmforum.org.subnetworkConnection.GradesOfImpact_T tolerableImpact, mtnm.tmforum.org.multiLayerSubnetwork.EMSFreedomLevel_T emsFreedomLevel, mtnm.tmforum.org.subnetworkConnection.TPDataList_THolder tpsToModify, mtnm.tmforum.org.subnetworkConnection.SubnetworkConnection_THolder theSNC, org.omg.CORBA.StringHolder errorReason) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void deleteSNC(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] sncName, mtnm.tmforum.org.multiLayerSubnetwork.EMSFreedomLevel_T emsFreedomLevel) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void deactivateAndDeleteSNC(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] sncName, mtnm.tmforum.org.subnetworkConnection.GradesOfImpact_T tolerableImpact, mtnm.tmforum.org.multiLayerSubnetwork.EMSFreedomLevel_T emsFreedomLevel, mtnm.tmforum.org.subnetworkConnection.TPDataList_THolder tpsToModify, mtnm.tmforum.org.subnetworkConnection.SubnetworkConnection_THolder theSNC, org.omg.CORBA.StringHolder errorReason) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void checkValidSNC(mtnm.tmforum.org.subnetworkConnection.SNCCreateData_T createData, mtnm.tmforum.org.subnetworkConnection.TPData_T[] tpsToModify, boolean considerResources, org.omg.CORBA.BooleanHolder valid) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getAllTPPools(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] subnetworkName, int how_many, mtnm.tmforum.org.terminationPoint.TerminationPointList_THolder tpList, mtnm.tmforum.org.terminationPoint.TerminationPointIterator_IHolder tpIt) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getAllTPPoolNames(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] subnetworkName, int how_many, mtnm.tmforum.org.globaldefs.NamingAttributesList_THolder nameList, mtnm.tmforum.org.globaldefs.NamingAttributesIterator_IHolder nameIt) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getRouteAndTopologicalLinks(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] sncName, mtnm.tmforum.org.subnetworkConnection.Route_THolder route, mtnm.tmforum.org.topologicalLink.TopologicalLinkList_THolder topologicalLinkList) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void setConjunctionSNC(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] sncName1, mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] sncName2, boolean operate) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void swapSNC(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] nameOfSNCtoBeDeactivated, mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] nameOfSNCtoBeActivated, mtnm.tmforum.org.multiLayerSubnetwork.EMSFreedomLevel_T emsFreedomLevel, mtnm.tmforum.org.subnetworkConnection.GradesOfImpact_T tolerableImpact, mtnm.tmforum.org.subnetworkConnection.TPDataList_THolder tpsToModify, mtnm.tmforum.org.subnetworkConnection.SNCState_THolder stateOfActivatedSNC, org.omg.CORBA.StringHolder errorReason) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getWaveLengthStatusByEndObject(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] aEndName, mtnm.tmforum.org.globaldefs.NameAndStringValue_T[][] inclusionNameList, mtnm.tmforum.org.globaldefs.NameAndStringValue_T[][] exclusionNameList, mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] zEndName, mtnm.tmforum.org.globaldefs.ConnectionDirection_T direction, mtnm.tmforum.org.subnetworkConnection.WaveLengthStatusList_THolder waveLengthStatusList) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getOrginalRoute(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] sncName, boolean includeHigherOrderCCs, mtnm.tmforum.org.subnetworkConnection.Route_THolder route) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getPresetRoute(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] sncName, int presetRouteID, mtnm.tmforum.org.subnetworkConnection.PresetRoute_THolder route) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getOrginalPresetRoute(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] sncName, int presetRouteID, mtnm.tmforum.org.subnetworkConnection.PresetRoute_THolder route) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void deletePresetRoute(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] sncName, int presetRouteID) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void createPresetRoute(mtnm.tmforum.org.subnetworkConnection.CreatePresetRouteData_T createData, mtnm.tmforum.org.subnetworkConnection.PresetRoute_THolder route) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getSharedRoute(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] sncName, int sharedRouteID, mtnm.tmforum.org.subnetworkConnection.SharedRoute_THolder route) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void deleteSharedRoute(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] sncName, int sharedRouteID) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void createSharedRoute(mtnm.tmforum.org.subnetworkConnection.CreateSharedRouteData_T createData, mtnm.tmforum.org.subnetworkConnection.SharedRoute_THolder route) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void switchRoute(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] sncName, java.lang.String routeId, mtnm.tmforum.org.subnetworkConnection.GradesOfImpact_T tolerableImpact, mtnm.tmforum.org.multiLayerSubnetwork.EMSFreedomLevel_T emsFreedomLevel, mtnm.tmforum.org.subnetworkConnection.TPDataList_THolder tpsToModify, mtnm.tmforum.org.globaldefs.NVSList_THolder additionalInfo, mtnm.tmforum.org.subnetworkConnection.SNCState_THolder sncState, org.omg.CORBA.StringHolder errorReason) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getSNCNamesByRouteModificationTime(java.lang.String utcBeginTime, int how_many, mtnm.tmforum.org.globaldefs.NamingAttributesList_THolder nameList, mtnm.tmforum.org.globaldefs.NamingAttributesIterator_IHolder nameIt) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getAllSNCNamesWithHigherOrderSNC(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] name, short[] connectivityRateList, mtnm.tmforum.org.globaldefs.NamingAttributesList_THolder nameList) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getAllMicrowaveLinksReport(java.lang.String destination, java.lang.String userName, java.lang.String password, mtnm.tmforum.org.notifications.NameAndAnyValue_T[] filter) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void setConjunctionSNCEx(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] sncName1, mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] sncName2, mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] additionalInfo, boolean operate) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getAllConjunctionSNCs(int how_many, mtnm.tmforum.org.multiLayerSubnetwork.HW_ConjunctionSNCList_THolder conjunctionSNCList, mtnm.tmforum.org.multiLayerSubnetwork.HW_ConjunctionSNCIterator_IHolder conjunctionSNCIt) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getConjunctionSNC(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] sncName1, mtnm.tmforum.org.globaldefs.NVSList_THolder sncName2, mtnm.tmforum.org.globaldefs.NVSList_THolder additionalInfo) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getServerConnections(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] clientName, mtnm.tmforum.org.subnetworkConnection.ServerTrailList_THolder serverInfoList) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
}
