package mtnm.tmforum.org.flowDomain_cmcc;


/**
 * Generated from IDL interface "FlowDomainMgr_cmcc_I".
 *
 * @author JacORB IDL compiler V 3.9
 * @version generated at 13/07/2021 04:51:40 PM
 */

public interface FlowDomainMgr_cmcc_IOperations
	extends mtnm.tmforum.org.common.Common_IOperations
{
	/* constants */
	/* operations  */
	void getAllFlowDomains(int how_many, mtnm.tmforum.org.flowDomain_cmcc.FDList_THolder flowDomains, mtnm.tmforum.org.flowDomain_cmcc.FDIterator_IHolder fdIt) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getFlowDomainsByUserLabel(java.lang.String userLabel, mtnm.tmforum.org.flowDomain_cmcc.FDList_THolder flowDomains) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getFlowDomain(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] fdName, mtnm.tmforum.org.flowDomain_cmcc.FlowDomain_THolder flowDomain) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getAssociatingFD(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] mfdName, mtnm.tmforum.org.flowDomain_cmcc.FlowDomain_THolder flowDomain) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getTransmissionParams(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] name, java.lang.String[] filter, mtnm.tmforum.org.transmissionParameters.LayeredParameterList_THolder transmissionParams) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void createFlowDomain(mtnm.tmforum.org.flowDomain_cmcc.FDCreateData_T createData, mtnm.tmforum.org.globaldefs.NamingAttributesList_THolder assignedCPTPs, mtnm.tmforum.org.subnetworkConnection.TPDataList_THolder tpsToModify, mtnm.tmforum.org.flowDomain_cmcc.FlowDomain_THolder theFD, org.omg.CORBA.StringHolder errorReason) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void deleteFlowDomain(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] fdName, mtnm.tmforum.org.subnetworkConnection.TPDataList_THolder tpsToModify, org.omg.CORBA.StringHolder errorReason) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void modifyFlowDomain(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] fdName, mtnm.tmforum.org.flowDomain_cmcc.FDModifyData_T fdModifyData, mtnm.tmforum.org.flowDomain_cmcc.FlowDomain_THolder modifiedFD, org.omg.CORBA.StringHolder failedAttributes, org.omg.CORBA.StringHolder errorReason) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void associateMFDsWithFlowDomain(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] fdName, mtnm.tmforum.org.globaldefs.NameAndStringValue_T[][] mfdNames, mtnm.tmforum.org.subnetworkConnection.TPDataList_THolder tpsToModify, org.omg.CORBA.StringHolder errorReason) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void deAssociateMFDsFromFlowDomain(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] fdName, mtnm.tmforum.org.globaldefs.NameAndStringValue_T[][] mfdNames, mtnm.tmforum.org.subnetworkConnection.TPDataList_THolder tpsToModify, org.omg.CORBA.StringHolder errorReason) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void associateCPTPsWithFlowDomain(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] fdName, mtnm.tmforum.org.globaldefs.NameAndStringValue_T[][] cptpNames, mtnm.tmforum.org.subnetworkConnection.TPDataList_THolder tpsToModify, org.omg.CORBA.StringHolder errorReason) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void deAssociateCPTPsFromFlowDomain(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] fdName, mtnm.tmforum.org.globaldefs.NameAndStringValue_T[][] tpNames, mtnm.tmforum.org.subnetworkConnection.TPDataList_THolder tpsToModify, org.omg.CORBA.StringHolder errorReason) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getAllAssociatedMFDs(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] tmdOrFdName, int how_many, mtnm.tmforum.org.flowDomain_cmcc.MFDList_THolder mfds, mtnm.tmforum.org.flowDomain_cmcc.MFDIterator_IHolder mfdIt) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getAllSupportedMFDs(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] holderName, int how_many, mtnm.tmforum.org.flowDomain_cmcc.MFDList_THolder mfds, mtnm.tmforum.org.flowDomain_cmcc.MFDIterator_IHolder mfdIt) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getMFD(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] mfdName, mtnm.tmforum.org.flowDomain_cmcc.MatrixFlowDomain_THolder mfd) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getAssigningMFD(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] cptpName, mtnm.tmforum.org.flowDomain_cmcc.MatrixFlowDomain_THolder mfd) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void createMFD(mtnm.tmforum.org.flowDomain_cmcc.MFDCreateData_T createData, mtnm.tmforum.org.subnetworkConnection.TPDataList_THolder tpsToModify, mtnm.tmforum.org.flowDomain_cmcc.MatrixFlowDomain_THolder theMFD, org.omg.CORBA.StringHolder errorReason) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void deleteMFD(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] mfdName, mtnm.tmforum.org.subnetworkConnection.TPDataList_THolder tpsToModify, org.omg.CORBA.StringHolder errorReason) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void modifyMFD(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] mfdName, mtnm.tmforum.org.flowDomain_cmcc.MFDModifyData_T mfdModifyData, mtnm.tmforum.org.flowDomain_cmcc.MatrixFlowDomain_THolder newMFD, org.omg.CORBA.StringHolder failedAttributes, org.omg.CORBA.StringHolder errorReason) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void assignCPTPsToMFD(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] mfdName, mtnm.tmforum.org.globaldefs.NameAndStringValue_T[][] tpNames, mtnm.tmforum.org.subnetworkConnection.TPDataList_THolder tpsToModify, org.omg.CORBA.StringHolder errorReason) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void unassignCPTPsFromMFD(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] mfdName, mtnm.tmforum.org.globaldefs.NameAndStringValue_T[][] tpNames, mtnm.tmforum.org.subnetworkConnection.TPDataList_THolder tpsToModify, org.omg.CORBA.StringHolder errorReason) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void createFTP(mtnm.tmforum.org.flowDomain_cmcc.FTPCreateData_T createData, mtnm.tmforum.org.subnetworkConnection.TPDataList_THolder tpsToModify, mtnm.tmforum.org.terminationPoint.TerminationPoint_THolder theFTP, org.omg.CORBA.StringHolder errorReason) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void deleteFTP(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] ftpName, mtnm.tmforum.org.subnetworkConnection.TPDataList_THolder tpsToModify, org.omg.CORBA.StringHolder errorReason) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getAllCPTPs(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] fdName, mtnm.tmforum.org.flowDomain_cmcc.CPTP_Role_T cptpRole, int how_many, mtnm.tmforum.org.terminationPoint.TerminationPointList_THolder cptpList, mtnm.tmforum.org.terminationPoint.TerminationPointIterator_IHolder cptpIt) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getAllAssignedCPTPs(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] mfdName, int how_many, mtnm.tmforum.org.terminationPoint.TerminationPointList_THolder cptpList, mtnm.tmforum.org.terminationPoint.TerminationPointIterator_IHolder cptpIt) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getAllAssignableCPTPs(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] mfdName, int how_many, mtnm.tmforum.org.terminationPoint.TerminationPointList_THolder cptpList, mtnm.tmforum.org.terminationPoint.TerminationPointIterator_IHolder cptpIt) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getAllFDFrs(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] fdName, int how_many, short[] connectivityRateList, mtnm.tmforum.org.flowDomainFragment_cmcc.FDFrList_THolder fdfrList, mtnm.tmforum.org.flowDomainFragment_cmcc.FDFrIterator_IHolder fdfrIt) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getFDFrsWithTP(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] cptpName, int how_many, mtnm.tmforum.org.flowDomainFragment_cmcc.FDFrList_THolder fdfrList, mtnm.tmforum.org.flowDomainFragment_cmcc.FDFrIterator_IHolder fdfrIt) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getFDFrsByUserLabel(java.lang.String userLabel, mtnm.tmforum.org.flowDomainFragment_cmcc.FDFrList_THolder fdfrs) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getFDFr(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] fdfrName, mtnm.tmforum.org.flowDomainFragment_cmcc.FlowDomainFragment_THolder fdfr) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void createAndActivateFDFr(mtnm.tmforum.org.flowDomainFragment_cmcc.FDFrCreateData_T createData, mtnm.tmforum.org.flowDomain_cmcc.ConnectivityRequirement_T connectivityRequirement, mtnm.tmforum.org.globaldefs.NameAndStringValue_T[][] aEnd, mtnm.tmforum.org.globaldefs.NameAndStringValue_T[][] zEnd, mtnm.tmforum.org.globaldefs.NamingAttributesList_THolder internalTPs, mtnm.tmforum.org.flowDomainFragment_cmcc.MatrixFlowDomainFragmentList_THolder mfdfrs, mtnm.tmforum.org.subnetworkConnection.TPDataList_THolder tpsToModify, mtnm.tmforum.org.flowDomainFragment_cmcc.FlowDomainFragment_THolder theFDFr, mtnm.tmforum.org.globaldefs.NamingAttributesList_THolder notConnectableCPTPList, mtnm.tmforum.org.globaldefs.NamingAttributesList_THolder parameterProblemsTPList, org.omg.CORBA.StringHolder errorReason) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void deactivateAndDeleteFDFr(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] fdfrName, mtnm.tmforum.org.subnetworkConnection.TPDataList_THolder tpsToModify, mtnm.tmforum.org.flowDomainFragment_cmcc.FlowDomainFragment_THolder theFDFr, org.omg.CORBA.StringHolder errorReason) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void modifyFDFr(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] fdfrName, mtnm.tmforum.org.flowDomainFragment_cmcc.FDFrModifyData_T fdfrModifyData, mtnm.tmforum.org.flowDomain_cmcc.ConnectivityRequirement_T connectivityRequirement, mtnm.tmforum.org.subnetworkConnection.TPDataList_THolder tpsToModify, mtnm.tmforum.org.globaldefs.NamingAttributesList_THolder failedTPList, mtnm.tmforum.org.globaldefs.NamingAttributesList_THolder parameterProblemsTPList, mtnm.tmforum.org.flowDomainFragment_cmcc.FlowDomainFragment_THolder newFDFr, org.omg.CORBA.StringHolder errorReason) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getAllTopologicalLinksOfFD(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] flowDomainName, int how_many, mtnm.tmforum.org.topologicalLink.TopologicalLinkList_THolder topoList, mtnm.tmforum.org.topologicalLink.TopologicalLinkIterator_IHolder topoIt) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void getFDFrRoute(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] fdfrName, mtnm.tmforum.org.flowDomainFragment_cmcc.FDFrRoute_THolder route) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void createFDFr(mtnm.tmforum.org.flowDomainFragment_cmcc.FDFrCreateData_T createData, mtnm.tmforum.org.flowDomain_cmcc.ConnectivityRequirement_T connectivityRequirement, mtnm.tmforum.org.subnetworkConnection.TPData_T[] aEnd, mtnm.tmforum.org.subnetworkConnection.TPData_T[] zEnd, mtnm.tmforum.org.globaldefs.NamingAttributesList_THolder internalTPs, mtnm.tmforum.org.flowDomainFragment_cmcc.MatrixFlowDomainFragmentList_THolder mfdfrs, mtnm.tmforum.org.subnetworkConnection.TPDataList_THolder tpsToModify, mtnm.tmforum.org.flowDomainFragment_cmcc.FlowDomainFragment_THolder theFDFr, org.omg.CORBA.StringHolder errorReason) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void activateFDFr(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] fdfrName, mtnm.tmforum.org.flowDomainFragment_cmcc.FlowDomainFragment_THolder fdfr) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void deactivateFDFr(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] fdfrName, mtnm.tmforum.org.flowDomainFragment_cmcc.FlowDomainFragment_THolder fdfr) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
	void deleteFDFr(mtnm.tmforum.org.globaldefs.NameAndStringValue_T[] fdfrName) throws mtnm.tmforum.org.globaldefs.ProcessingFailureException;
}
